version: '3.1'
services:
  # mysql
  mysql:
    image: mysql:5.7
    container_name: apollo-mysql
    networks:
      - apollo
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - './sql:/docker-entrypoint-initdb.d'
  # configservice
  configservice:
    image: apolloconfig/apollo-configservice:1.9.1
    container_name: apollo-configservice
    networks:
      - apollo
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ApolloConfigDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - mysql
  # adminservice
  adminservice:
    image: apolloconfig/apollo-adminservice:1.9.1
    container_name: apollo-adminservice
    networks:
      - apollo
    ports:
      - 8090:8090
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ApolloConfigDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - mysql
      - configservice
  # portal
  portal:
    image: apolloconfig/apollo-portal:1.9.1
    container_name: apollo-portal
    networks:
      - apollo
    ports:
      - 8070:8070
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ApolloPortalDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - mysql
      - adminservice
# network
networks:
  apollo:
    name: apollo
    driver: bridge