version: '3.1'
services:
  # mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - apollo
    command: --default-authentication-plugin=mysql_native_password # 指定使用插件
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456' # root用户密码
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d' # 初始化sql
  # apollo
  apollo:
    image: apolloconfig/apollo-configservice:1.9.1
    container_name: apollo
    networks:
      - apollo
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ApolloConfigDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - mysql

networks:
  apollo:
    name: apollo
    driver: bridge