apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  type: NodePort
  ports:
  - name: db
    nodePort: 30920
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    nodePort: 30930
    port: 9300
    protocol: TCP
    targetPort: 9300    
  selector:
    run: elasticsearch
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: elasticsearch
  name: elasticsearch
  namespace: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      run: elasticsearch
  strategy: {}
  template:
    metadata:
      labels:
        run: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.14.1
          ports:
            - name: db
              containerPort: 9200
              protocol: TCP
            - name: tramsport
              containerPort: 9300
              protocol: TCP
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: '-Xms512m -Xmx512m'
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi