# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "k8s-node-#{i}" do |node|
      config.vm.box = "centos/7"
      # 设置虚拟机的主机名
      node.vm.hostname="k8s-node-#{i}"
      # 设置虚拟机的IP
      node.vm.network "private_network", ip: "192.168.56.#{99+i}", netmask: "255.255.255.0"
      # VirtaulBox相关配置
      node.vm.provider "virtualbox" do |v|
        # 设置虚拟机的名称
        v.name = "k8s-node-#{i}"
        # 设置虚拟机的内存大小
        v.memory = 2048
        # 设置虚拟机的CPU个数
        v.cpus = 2
      end
    end
  end
end
