# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # 设置虚拟机的Box
  config.vm.box = "zhaoyunxing/centos-k8s"
  config.vm.box_version = "0.0.1"
  # 设置root用户
  config.ssh.username = "vagrant" 
  config.ssh.password = "vagrant"
  # file sync disabled
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # master
  config.vm.define "k8s-master" do |master|
    # set hostname
    master.vm.hostname="k8s-master"
    # master init
    master.vm.provision "shell", path:"script/node_init.sh"
    # set port
    master.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh"
    # set network
    master.vm.network "private_network", ip: "192.168.56.200", netmask: "255.255.255.0"
    # set memory、cpu
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      # 设置virtualbox显示名称
      vb.name = "k8s-master"
      # 设置cpu
      vb.cpus=2
    end
  end
  
  # node
  (1..2).each do |i|
       config.vm.define "k8s-node#{i}" do |node|
           # 设置虚拟机的主机名
           node.vm.hostname="k8s-node#{i}"
           # set ssh port
           node.vm.network "forwarded_port", guest: 22, host:"#{2200+i}", id: "ssh"
           # 设置虚拟机的IP
           node.vm.network "private_network", ip: "192.168.56.#{200+i}", netmask: "255.255.255.0"
           # node init
           node.vm.provision "shell", path:"script/node_init.sh"
           # VirtaulBox相关配置
           node.vm.provider "virtualbox" do |vb|
               # 设置虚拟机的名称
               vb.name = "k8s-node#{i}"
               # 设置虚拟机的内存大小
               vb.memory = 2048
               # 设置虚拟机的CPU个数
               vb.cpus = 2
           end
       end
  end
end
