# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # 设置虚拟机的Box
  config.vm.box = "zhaoyunxing/centos-docker"
  config.vm.box_version = "0.0.1"
  # 设置vagrant名称
  config.vm.define "centos-k8s"
  config.vm.hostname="centos-k8s"
  # 设置密码
  config.ssh.username = "vagrant" 
  config.ssh.password = "vagrant"
  # file sync disabled
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # isntall k8s
  config.vm.provision "shell", path:"script/k8s_install.sh"
  # set memory、cpu
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    # 设置virtualbox显示名称
    vb.name = "centos-k8s"
    # 设置cpu
    vb.cpus=2
  end
end
