Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  # 设置主机名称
  config.vm.hostname="centos-docker"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "centos-docker"
    # 设置cpu
    vb.cpus=2
  end
  config.vm.provision "shell", path:"docker_install.sh"
end