# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"
  # 设置主机名称
  config.vm.hostname="centos-docker"
  # 设置ssh端口
  #config.ssh.port=1234
  # 设置ssh用户名zo
  #config.ssh.username="ubi"
  # 设置ssh密码
  #config.ssh.password="123456"
  # 
  #config.ssh.insert_key=false
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = falsezo


  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  #config.vm.network "forwarded_port", guest: 22, host: 2222, id:"ssh", disabled:"true"
  #config.vm.network "forwarded_port", guest: 22, host: 1234

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # 设置私有ip
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network", ip: "192.168.251.10"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     #vb.gui = true
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
     # 设置virtualbox显示名称
     vb.name = "centos-docker"
     # 设置cpu
     vb.cpus=2
   end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL
      sudo yum install -y yum-utils device-mapper-persistent-data lvm2
      sudo yum remove docker docker-common  docker-selinux docker-engine
      sudo yum-config-manager -y --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      sudo yum -y install docker-ce
      sudo usermod -aG docker $USER
      sudo systemctl start docker
      sudo chmod a+rw /var/run/docker.sock
      sudo systemctl restart docker
   SHELL
end