version: '3.1'

services:

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    container_name: mongo
    volumes:
      - ~/data/mongo:/data/db  
  
  express:
    depends_on:
      - mongo
    container_name: mg-express  
    image: mongo-express:0.54.0
    ports:
      - 8010:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
