Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell", path:"script/docker_install.sh"
  # 系统配置
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    # 显示名字
    vb.name = "centos-docker"
    # 设置cpu
    vb.cpus=2
  end
end