Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  # 设置虚拟机的Box
  config.vm.box = "centos-docker"
  # 设置版本
  config.vm.box_version = "0.0.1"
  # 系统配置
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    # 显示名字
    vb.name = "centos-docker"
    # 设置cpu
    vb.cpus=2
  end
  config.vm.provision "shell", path:"script/docker_install.sh"
  # push
  config.push.define "heroku" do |push|
    push.app = "zhaoyunxing/centos-docker"
  end
end